### ISSUE TITLE
Image overflowing on mobile screens

### ISSUE THREAD

**Issue by sangyeon217** [sangyeon217/sangyeon217.github.io#8]
**Describe the bug**
Images are overflowing on mobile screens

**Screenshots**
![image_overflow](https://user-images.githubusercontent.com/71223871/98828388-5cb6e700-247b-11eb-87c3-a945966941ca.png)

**Comment by sangyeon217** [comment]
화면이 이미지의 크기보다 작아지면, 화면크기에 맞춰서 크기가 줄어들도록 이미지 요소에 대한 CSS 수정 필요.

```css
img {
  width: 100%;
  height: auto;
}
```
